# Generated by Django 5.2.5 on 2025-09-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
