# Generated by Django 5.2.5 on 2025-09-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_noticia_imagen_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_inicial', models.CharField(default='Bienvenido a CyberSec', max_length=200)),
                ('descripcion_inicial', models.TextField(default='Tu fuente de noticias y herramientas de ciberseguridad.')),
            ],
        ),
    ]
