# Generated by Django 5.2.5 on 2025-09-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_herramienta', models.CharField(max_length=100)),
                ('descripcion_herramienta', models.TextField()),
                ('url_herramienta', models.URLField()),
            ],
        ),
    ]
