# Generated by Django 5.2.5 on 2025-09-04 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_herramienta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herramienta',
            old_name='descripcion_herramienta',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='herramienta',
            old_name='nombre_herramienta',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='herramienta',
            old_name='url_herramienta',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='inicio',
            old_name='descripcion_inicial',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='inicio',
            old_name='titulo_inicial',
            new_name='titulo',
        ),
    ]
