# Generated by Django 5.2.5 on 2025-09-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_descripcion_herramienta_herramienta_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inicio',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
