# Generated by Django 5.2.5 on 2025-09-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_inicio_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='descripcion',
            field=models.TextField(default='ej: Tu fuente de noticias y herramientas de ciberseguridad.'),
        ),
    ]
