# Generated by Django 5.2.5 on 2025-09-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_herramienta_imagen_url_alter_inicio_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='fuente',
            field=models.URLField(blank=True, null=True),
        ),
    ]
