# Generated by Django 5.2.5 on 2025-09-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_noticia_fuente'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='link_noticia',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fuente',
            field=models.TextField(blank=True, null=True),
        ),
    ]
